version: 2

models:
  - name: dim_customer
    columns:              
      - name: customer_id
        tests:
          - not_null
          - unique
  - name: dim_employee
    columns:              
      - name: employee_id
        tests:
          - not_null
          - unique
  - name: dim_product
    columns:              
      - name: product_id
        tests:
          - not_null
          - unique
  - name: dim_date
    columns:              
      - name: full_date
        tests:
          - not_null
          - unique
  - name: fact_sales
    columns:              
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - relationships:
              to: "{{ ref('dim_customer') }}"
              field: customer_id
      - name: employee_id
        tests:
          - relationships:
              to: "{{ ref('dim_employee') }}"
              field: employee_id
      - name: product_id
        tests:
          - relationships:
              to: "{{ ref('dim_product') }}"
              field: product_id
      - name: order_date
        tests:
          - not_null
          - relationships:
              to: "{{ ref('dim_date') }}"
              field: full_date
  - name: fact_purchase_order
    columns:              
      - name: id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - relationships:
              to: "{{ ref('dim_customer') }}"
              field: customer_id
      - name: employee_id
        tests:
          - relationships:
              to: "{{ ref('dim_employee') }}"
              field: employee_id
      - name: product_id
        tests:
          - relationships:
              to: "{{ ref('dim_product') }}"
              field: product_id
      - name: creation_date
        tests:
          - not_null
          - relationships:
              to: "{{ ref('dim_date') }}"
              field: full_date
